#!/usr/bin/env python3
"""Generate the bundled native scenarios at a requested map dimension.

The bundled scenarios used to be hand-written 24x16 maps. The map sizes the
original engine actually generates are 120..255 tiles square (see
../docs/fidelity/RANDOM_MAP_FIDELITY.md for the decompiled switch), and the app now presents
only the recovered maximum, so these are emitted at 255x255 from the layouts
below instead of being edited by hand.

Every layout is its original 24x16 form, expressed once as a source grid,
scaled to the requested dimension by two rules:

* Terrain and elevation directives describe *areas*. A source tile
  ``(x, y)`` covers the output half-open cell ``[x*W/W0, (x+1)*W/W0)``, so a
  source rect ``l..r`` becomes ``round(l*W/W0) .. round((r+1)*W/W0)-1``.
  This keeps a one-tile river one scaled cell wide instead of collapsing it.
* Unit and building placements describe *points*. They land on the top-left
  tile of their scaled cell, ``round(x*W/W0)``.

Rounding is half-up so the mapping is independent of Python's banker's
rounding. The generator validates every emitted placement against the
terrain it lands on and fails rather than writing an unloadable map.

Layouts are named on the command line; with no names, all of them are
written. ``--check`` verifies the checked-in files match the generator.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


SOURCE_WIDTH = 24
SOURCE_HEIGHT = 16

# Terrain that a unit or building may legally occupy.
WALKABLE = {"grass", "beach", "shallows"}

# Footprint sizes of the buildings these scenarios place, from
# src/game_rules.cpp. Only what is needed to validate placements.
BUILDING_FOOTPRINTS = {"town_center": (4, 4)}

# One line only: the header record must stay on line 2 and the map record on
# line 3, which is what the fidelity checks read.
HEADER = "# Generated by tools/generate_demo_scenario.py; do not edit by hand."

PREAMBLE = [
    "economy blue 250 200 100 200",
    "economy red 250 200 100 200",
    "age blue dark",
    "age red dark",
]


class Layout:
    """One bundled scenario, described over the original 24x16 grid."""

    def __init__(
        self,
        name: str,
        version: int,
        terrain_groups: list[tuple[str, list[tuple[str, int, int, int, int]]]],
        units: list[tuple[str, str, int, int]],
        buildings: list[tuple[str, str, int, int]],
        directives: list[str] | None = None,
        elevation: list[tuple[int, int, int]] | None = None,
    ) -> None:
        self.name = name
        self.version = version
        self.terrain_groups = terrain_groups
        self.units = units
        self.buildings = buildings
        # Records that must sit between the map record and the economy
        # block, in the order the original file had them.
        self.directives = directives or []
        # (x, y, level) over the source grid; scaled as areas.
        self.elevation = elevation or []


LAYOUTS = {
    # The startup map: a river with a ford, forests, and mineral deposits.
    "demo.scenario": Layout(
        name="demo.scenario",
        version=27,
        terrain_groups=[
            (
                "River with a scaled two-cell crossing.",
                [
                    ("water", 11, 0, 11, 15),
                    ("grass", 11, 7, 11, 7),
                    ("grass", 11, 8, 11, 8),
                ],
            ),
            (
                "Forest resource groups.",
                [
                    ("forest", 3, 2, 6, 5),
                    ("forest", 17, 10, 20, 13),
                ],
            ),
            (
                "Food and mineral deposits.",
                [
                    ("berries", 7, 3, 8, 4),
                    ("gold", 8, 11, 9, 12),
                    ("stone", 14, 3, 15, 4),
                ],
            ),
        ],
        units=[
            ("villager", "blue", 2, 7),
            ("sheep", "blue", 3, 7),
            ("sheep", "blue", 4, 7),
            ("deer", "red", 7, 6),
            ("boar", "red", 15, 9),
            ("scout_cavalry", "blue", 4, 9),
            ("villager", "red", 21, 8),
            ("scout_cavalry", "red", 19, 6),
        ],
        buildings=[
            ("town_center", "blue", 0, 10),
            ("town_center", "red", 20, 0),
        ],
    ),
    # Mission two of briefing-demo.campaign: a stepped hill between the
    # two starts. It is loaded through the same playable-map guard as the
    # startup scenario, so it has to be the maximum dimension too.
    "elevation-demo.scenario": Layout(
        name="elevation-demo.scenario",
        version=63,
        directives=["trigger_syntax strict"],
        terrain_groups=[
            (
                "Forest and gold away from the hill.",
                [
                    ("forest", 12, 3, 14, 5),
                    ("gold", 8, 11, 9, 12),
                ],
            ),
        ],
        elevation=[
            (x, y, level)
            for y, row in enumerate(
                [
                    [1, 1, 1, 1, 1],
                    [1, 2, 2, 2, 1],
                    [1, 2, 3, 2, 1],
                    [1, 2, 2, 2, 1],
                    [1, 1, 1, 1, 1],
                ],
                start=6,
            )
            for x, level in enumerate(row, start=4)
        ],
        units=[
            ("archer", "blue", 6, 8),
            ("villager", "blue", 5, 9),
            ("archer", "red", 9, 8),
            ("villager", "red", 10, 9),
        ],
        buildings=[
            ("town_center", "blue", 1, 10),
            ("town_center", "red", 18, 1),
        ],
    ),
}


def half_up(value: float) -> int:
    """Round half away from zero, independent of Python's round()."""
    return int(value + 0.5) if value >= 0 else -int(-value + 0.5)


def scale_point(x: int, y: int, width: int, height: int) -> tuple[int, int]:
    return (
        min(half_up(x * width / SOURCE_WIDTH), width - 1),
        min(half_up(y * height / SOURCE_HEIGHT), height - 1),
    )


def scale_rect(
    left: int,
    top: int,
    right: int,
    bottom: int,
    width: int,
    height: int,
) -> tuple[int, int, int, int]:
    out_left, out_top = scale_point(left, top, width, height)
    out_right = min(
        half_up((right + 1) * width / SOURCE_WIDTH) - 1, width - 1
    )
    out_bottom = min(
        half_up((bottom + 1) * height / SOURCE_HEIGHT) - 1, height - 1
    )
    return out_left, out_top, max(out_right, out_left), max(
        out_bottom, out_top
    )


def build(layout: Layout, width: int, height: int) -> str:
    if not 1 <= width <= 255 or not 1 <= height <= 255:
        raise ValueError("map dimensions must be within 1..255")

    terrain = [["grass"] * width for _ in range(height)]
    lines = [HEADER]
    lines.append(f"AOE-ARCHAEOLOGY-SCENARIO {layout.version}")
    lines.append(f"map {width} {height}")
    lines.extend(layout.directives)
    lines.extend(PREAMBLE)

    for comment, group in layout.terrain_groups:
        lines.append("")
        lines.append(f"# {comment}")
        for kind, left, top, right, bottom in group:
            sl, st, sr, sb = scale_rect(
                left, top, right, bottom, width, height
            )
            lines.append(f"terrain_rect {kind} {sl} {st} {sr} {sb}")
            for y in range(st, sb + 1):
                for x in range(sl, sr + 1):
                    terrain[y][x] = kind

    if layout.elevation:
        lines.append("")
        lines.append("# Stepped hill, each source tile scaled to a cell.")
        for x, y, level in layout.elevation:
            sl, st, sr, sb = scale_rect(x, y, x, y, width, height)
            for cell_y in range(st, sb + 1):
                for cell_x in range(sl, sr + 1):
                    lines.append(f"elevation {cell_x} {cell_y} {level}")

    occupied: dict[tuple[int, int], str] = {}

    lines.append("")
    for kind, owner, x, y in layout.buildings:
        sx, sy = scale_point(x, y, width, height)
        footprint_width, footprint_height = BUILDING_FOOTPRINTS[kind]
        if (
            sx + footprint_width > width
            or sy + footprint_height > height
        ):
            raise ValueError(
                f"{kind} at {sx},{sy} leaves the {width}x{height} map"
            )
        for fy in range(sy, sy + footprint_height):
            for fx in range(sx, sx + footprint_width):
                if terrain[fy][fx] not in WALKABLE:
                    raise ValueError(
                        f"{kind} footprint tile {fx},{fy} is "
                        f"{terrain[fy][fx]}, not walkable"
                    )
                if (fx, fy) in occupied:
                    raise ValueError(
                        f"{kind} footprint tile {fx},{fy} already holds "
                        f"{occupied[(fx, fy)]}"
                    )
                occupied[(fx, fy)] = f"{owner} {kind}"
        lines.append(f"building {kind} {owner} {sx} {sy}")

    lines.append("")
    for kind, owner, x, y in layout.units:
        sx, sy = scale_point(x, y, width, height)
        if terrain[sy][sx] not in WALKABLE:
            raise ValueError(
                f"{kind} at {sx},{sy} stands on {terrain[sy][sx]}"
            )
        if (sx, sy) in occupied:
            raise ValueError(
                f"{kind} at {sx},{sy} collides with {occupied[(sx, sy)]}"
            )
        occupied[(sx, sy)] = f"{owner} {kind}"
        lines.append(f"unit {kind} {owner} {sx} {sy}")

    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--width", type=int, default=255)
    parser.add_argument("--height", type=int, default=255)
    parser.add_argument(
        "--resources",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "resources",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if an output file differs from generated content",
    )
    parser.add_argument(
        "layouts",
        nargs="*",
        choices=sorted(LAYOUTS),
        help="layouts to write; all of them when omitted",
    )
    arguments = parser.parse_args(argv)

    selected = arguments.layouts or sorted(LAYOUTS)
    status = 0
    for name in selected:
        layout = LAYOUTS[name]
        content = build(layout, arguments.width, arguments.height)
        output = arguments.resources / name
        if arguments.check:
            existing = output.read_text() if output.exists() else ""
            if existing != content:
                print(
                    f"{output} is stale; rerun "
                    "tools/generate_demo_scenario.py",
                    file=sys.stderr,
                )
                status = 1
            else:
                print(f"{output} matches the generator")
            continue
        output.write_text(content)
        print(
            f"wrote {output} at {arguments.width}x{arguments.height}"
        )
    return status


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
