#!/usr/bin/env python3
"""Generate Technology-to-DAT-icon C++ switch from tracked audit evidence."""

from __future__ import annotations

import json
import pathlib
import re
import sys


def main() -> int:
    root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    check_only = "--check" in sys.argv[2:]
    catalog = json.loads(
        (root / "generated/ui_icon_catalog.json").read_text(encoding="utf-8")
    )
    icons = {
        record["name"]: record["dat_icon_id"]
        for record in catalog["items"]
        if record["category"] == "technology"
        and record["dat_icon_classification"] == "exact"
        and isinstance(record["dat_icon_id"], int)
    }
    types = (root / "include/aoe/types.hpp").read_text(encoding="utf-8")
    match = re.search(
        r"enum\s+class\s+Technology\s*\{(?P<body>.*?)\};",
        types,
        re.DOTALL,
    )
    if not match:
        raise ValueError("Technology enum not found")
    names = [
        token.strip()
        for token in match.group("body").split(",")
        if token.strip()
    ]
    missing = [name for name in names if name not in icons]
    lines = [
        "// Generated by tools/generate_technology_icon_bindings.py.",
        "// Source: generated/ui_icon_catalog.json.",
    ]
    lines.extend(
        (
            f"case Technology::{name}: return technology({icons[name]});"
            if name in icons
            else f"case Technology::{name}: return std::nullopt;"
        )
        for name in names
    )
    output = (
        root / "include/aoe/generated/technology_icon_bindings.inc"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    generated = "\n".join(lines) + "\n"
    if check_only:
        if not output.exists() or output.read_text(
            encoding="utf-8"
        ) != generated:
            print("technology icon bindings are stale")
            return 1
    else:
        output.write_text(generated, encoding="utf-8")
    print(
        f"generated {len(names) - len(missing)} exact bindings; "
        f"{len(missing)} explicit fallbacks"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
